# services/report_service.py
#
# Generates PDF medication reports for a profile using WeasyPrint + Jinja2.
# IDOR: profile_id verified against user_id before any data is read.
# PHI handling: PDF saved to /tmp with UUID filename, link expires in 1 hour.

import os
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from core.config import settings
from core.exceptions import PDFGenerationError, ProfileNotFoundError
from models.user import Medication, Profile
from monitoring.audit import AuditEventType, AuditLogger, AuditOutcome
from monitoring.logger import get_logger
from schemas.all_schemas import ReportResponse

logger = get_logger(__name__)

REPORT_EXPIRY_HOURS = 1


class ReportService:

    def __init__(self, db: AsyncSession):
        self.db = db
        self.audit = AuditLogger(db=db)

    async def generate_report(
        self,
        profile_id: str,
        user_id: str,
        include_inactive: bool = False,
        request_id: str = "unknown",
    ) -> ReportResponse:
        # IDOR check: profile must belong to user_id
        profile_result = await self.db.execute(
            select(Profile).where(Profile.id == profile_id, Profile.user_id == user_id)
        )
        profile = profile_result.scalar_one_or_none()
        if not profile:
            raise ProfileNotFoundError(profile_id=profile_id)

        # Fetch medications (already IDOR-safe — profile is verified)
        med_query = select(Medication).where(Medication.profile_id == profile_id)
        if not include_inactive:
            med_query = med_query.where(Medication.is_active == True)
        med_result = await self.db.execute(med_query)
        medications = list(med_result.scalars().all())

        try:
            html_content = self._render_html(profile=profile, medications=medications)
            pdf_path = await self._generate_pdf(html_content)
        except Exception as error:
            logger.error("report_generation_failed", error=str(error), profile_id=profile_id)
            raise PDFGenerationError()

        report_id = str(uuid.uuid4())
        expires_at = datetime.now(tz=timezone.utc) + timedelta(hours=REPORT_EXPIRY_HOURS)

        await self.audit.log(
            event_type=AuditEventType.REPORT_GENERATED,
            outcome=AuditOutcome.SUCCESS,
            user_id=user_id,
            profile_id=profile_id,
            resource_type="report",
            resource_id=report_id,
            request_id=request_id,
        )

        logger.info("report_generated", profile_id=profile_id, medication_count=len(medications))

        return ReportResponse(
            report_id=report_id,
            download_url=f"/api/v1/reports/download/{report_id}",
            expires_at=expires_at,
            medication_count=len(medications),
        )

    def _render_html(self, profile: Profile, medications: list) -> str:
        """
        Renders the report as HTML using a simple inline template.
        WHY HTML FIRST: WeasyPrint converts HTML+CSS to PDF — this is the
        standard pattern for generating styled PDFs from Python.
        """
        from jinja2 import Template

        template = Template("""
        <html>
        <head>
        <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1a1a1a; }
            h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background: #f3f4f6; text-align: left; padding: 10px; border-bottom: 2px solid #d1d5db; }
            td { padding: 10px; border-bottom: 1px solid #e5e7eb; }
            .disclaimer { margin-top: 40px; font-size: 11px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 15px; }
            .meta { color: #6b7280; font-size: 13px; }
        </style>
        </head>
        <body>
            <h1>Pillara Medication Report</h1>
            <p class="meta">Profile: {{ profile_name }}</p>
            <p class="meta">Generated: {{ generated_date }}</p>

            <table>
                <tr><th>Medication</th><th>Dosage</th><th>Frequency</th><th>Purpose</th><th>Status</th></tr>
                {% for med in medications %}
                <tr>
                    <td>{{ med.name }}</td>
                    <td>{{ med.dosage or '—' }}</td>
                    <td>{{ med.frequency or '—' }}</td>
                    <td>{{ med.purpose or '—' }}</td>
                    <td>{{ 'Active' if med.is_active else 'Discontinued' }}</td>
                </tr>
                {% endfor %}
            </table>

            <p class="disclaimer">
                This report is generated by Pillara for informational purposes only.
                It is not a substitute for professional medical advice.
                Please share this report with your doctor or pharmacist and consult
                them before making any changes to your medications.
            </p>
        </body>
        </html>
        """)

        return template.render(
            profile_name=profile.name,
            generated_date=datetime.now(tz=timezone.utc).strftime("%B %d, %Y"),
            medications=medications,
        )

    async def _generate_pdf(self, html_content: str) -> str:
        """Converts HTML to PDF and saves with a UUID filename."""
        import asyncio
        from weasyprint import HTML

        os.makedirs(settings.PDF_STORAGE_PATH, exist_ok=True)
        pdf_filename = f"{uuid.uuid4()}.pdf"
        pdf_path = os.path.join(settings.PDF_STORAGE_PATH, pdf_filename)

        def _sync_generate():
            HTML(string=html_content).write_pdf(pdf_path)

        await asyncio.to_thread(_sync_generate)
        return pdf_path